---
- name: Install Nginx
  become: true 
  apt: 
    name: nginx
    state: latest
    update_cache: yes

- name: copy nginx config file
  become: true 
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-enabled/default.conf mode=0644

- name: enable configuration
  become: true 
  file: >
    src=/etc/nginx/sites-enabled/default.conf
    dest=/etc/nginx/sites-available/{{ domen_name }}.conf
    state=link

- name: copy index.html 
  become: true    
  template: src=index.html.j2 dest=/var/www/html/index.html mode=0644

- name: Change permission on folder
  become: true  
  file: path=/var/www/html  mode=775 state=directory owner=www-data group=www-data recurse=yes
  notify:
    - restart-nginx

